<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Booking;
use Doctrine\ORM\EntityRepository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends EntityRepository
{
    /**
     * Find bookings for given room and dates.
     *
     * @param Booking $booking
     *   The booking to get data from.
     * @param boolean $validated
     *   Only check for validated bookings if true.
     *
     * @return array
     *   All bookings for given room and dates.
     */
    public function findExisting(Booking $booking, $validated = true)
    {
        $qb = $this->createQueryBuilder('booking')
            ->addSelect('booking')
            ->andWhere('booking.room = :room')
            ->andWhere('booking.fromDate >= :start AND booking.fromDate <= :end')   // start overlaps
            ->orWhere('booking.toDate >= :start AND booking.toDate <= :end')        // end overlaps
            ->orWhere('booking.fromDate <= :start AND booking.toDate >= :end')      // large booking over asked dates
            ->orWhere('booking.fromDate >= :start AND booking.toDate <= :end')      // booking inside asked dates
            ->setParameter('room', $booking->getRoom())
            ->setParameter('start', $booking->getFromDate())
            ->setParameter('end', $booking->getToDate());

        if ($validated) {
            $qb
                ->andWhere('booking.validated = :validated')
                ->setParameter('validated', true);
        }

        return $qb->getQuery()->getResult();
    }
}
