_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

homepage:
    path:     /{_locale}
    defaults: { _controller: AppBundle:Home:index, _locale: fr }
    requirements:
        _locale: en|fr

room_red:
    path:     /{_locale}/chambre/rubis
    defaults: { _controller: AppBundle:Room:redRoom }
    requirements:
        _locale: en|fr

room_green:
    path:     /{_locale}/chambre/opale
    defaults: { _controller: AppBundle:Room:greenRoom }
    requirements:
        _locale: en|fr

room_blue:
    path:     /{_locale}/chambre/saphir
    defaults: { _controller: AppBundle:Room:blueRoom }
    requirements:
        _locale: en|fr

booking:
    path:     /{_locale}/reservation
    defaults: { _controller: AppBundle:Booking:index }
    requirements:
        _locale: en|fr

calendar_render_ajax:
    path:     /{_locale}/calendar/render/ajax
    defaults: { _controller: AppBundle:Calendar:render }
    requirements:
        _locale: en|fr

contact:
    path:     /{_locale}/contact-us
    defaults: { _controller: AppBundle:Contact:index }
    requirements:
        _locale: en|fr

admin_dashboard:
    path:     /admin/dashboard
    defaults: { _controller: AppBundle:Admin:index }